# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pylint

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with pylint
      run: |
        pip install pylint
        score=$(python pylint_score.py --score)
        color=$(python pylint_score.py --color)
        echo "Score:$score, Color:$color"
        echo "PYLINT_SCORE=$score/10.00" >> $GITHUB_ENV
        echo "PYLINT_COLOR=$color" >> $GITHUB_ENV
    - name: Create Pylint Badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 00ce73155619a4544884ca6d251954b3
        filename: pylint_badge.json
        label: Pylint
        message: ${{ env.PYLINT_SCORE }}
        color: ${{ env.PYLINT_COLOR }}
        style: plastic